from easydict import EasyDict

atari_env_action_space_map = EasyDict({
    'ALE/Alien-v5': 18,
    'ALE/Amidar-v5': 10,
    'ALE/Assault-v5': 7,
    'ALE/Asterix-v5': 9,
    'ALE/BankHeist-v5': 18,
    'ALE/BattleZone-v5': 18,
    'ALE/ChopperCommand-v5': 18,
    'ALE/CrazyClimber-v5': 9,
    'ALE/DemonAttack-v5': 6,
    'ALE/Freeway-v5': 3,
    'ALE/Frostbite-v5': 18,
    'ALE/Gopher-v5': 8,
    'ALE/Hero-v5': 18,
    'ALE/Jamesbond-v5': 18,
    'ALE/Kangaroo-v5': 18,
    'ALE/Krull-v5': 18,
    'ALE/KungFuMaster-v5': 14,
    'ALE/PrivateEye-v5': 18,
    'ALE/RoadRunner-v5': 18,
    'ALE/UpNDown-v5': 6,
    'ALE/Pong-v5': 6,
    'ALE/MsPacman-v5': 9,
    'ALE/Qbert-v5': 6,
    'ALE/Seaquest-v5': 18,
    'ALE/Boxing-v5': 18,
    'ALE/Breakout-v5': 4,
    'ALE/SpaceInvaders-v5': 6,
    'ALE/BeamRider-v5': 9,
    'ALE/Gravitar-v5': 18,
})