from easydict import EasyDict

atari_env_action_space_map = EasyDict({
    'AlienNoFrameskip-v4': 18,
    'AmidarNoFrameskip-v4': 10,
    'AssaultNoFrameskip-v4': 7,
    'AsterixNoFrameskip-v4': 9,
    'BankHeistNoFrameskip-v4': 18,
    'BattleZoneNoFrameskip-v4': 18,
    'ChopperCommandNoFrameskip-v4': 18,
    'CrazyClimberNoFrameskip-v4': 9,
    'DemonAttackNoFrameskip-v4': 6,
    'FreewayNoFrameskip-v4': 3,
    'FrostbiteNoFrameskip-v4': 18,
    'GopherNoFrameskip-v4': 8,
    'HeroNoFrameskip-v4': 18,
    'JamesbondNoFrameskip-v4': 18,
    'KangarooNoFrameskip-v4': 18,
    'KrullNoFrameskip-v4': 18,
    'KungFuMasterNoFrameskip-v4': 14,
    'PrivateEyeNoFrameskip-v4': 18,
    'RoadRunnerNoFrameskip-v4': 18,
    'UpNDownNoFrameskip-v4': 6,
    'PongNoFrameskip-v4': 6,
    'MsPacmanNoFrameskip-v4': 9,
    'QbertNoFrameskip-v4': 6,
    'SeaquestNoFrameskip-v4': 18,
    'BoxingNoFrameskip-v4': 18,
    'BreakoutNoFrameskip-v4': 4,
})